org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

modId=blockui
modGroup=com.ldtteam
modVersion=0.0.1

javaVersion=25
useJavaToolChains=true

#The currently running forge.
forgeVersion=26.1.2.33-beta

fml_range=[4,)
forge_range=[26.1.2,)
minecraft_range=[26.1.2, 27)

#The version for forge (dependency)
exactMinecraftVersion=26.1.2
#The main version on curseforge
minecraftVersion=26.1.2
#Semicolon seperated list of mc versions, which are marked as compatible on curseforge
additionalMinecraftVersions=

githubUrl=https://github.com/ldtteam/BlockUI
gitUrl=https://github.com/ldtteam/BlockUI.git
gitConnectUrl=https://github.com/ldtteam/BlockUI.git
projectUrl=https://github.com/ldtteam/BlockUI

curseId=522992
usesCurse=true

useDefaultTestSystem=true
runtimeSourceSets=main
projectHasApi=false
