org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

local.version=0.0.1

javaVersion=25

modId=blockui
type=MOD
description=XML Based Minecraft UI Library

#The currently running forge.
neoforge.version=26.1.0.0-alpha.11+snapshot-7

curseId=522992
usesCurse=true

### Minecraft
minecraft.version=26.1-snapshot-7
minecraft.additionalVersions=

useDefaultTestSystem=true
runtimeSourceSets=main
projectHasApi=false
