modLoader="javafml" #mandatory
license="GPL3"
loaderVersion="[4,)" #mandatory
issueTrackerURL="https://github.com/ldtteam/BlockUI/issues/new/choose"
[[mods]] #mandatory
modId="blockui" #mandatory
version="${file.jarVersion}" #mandatory
displayName="BlockUI" #mandatory
authors="LDTTeam" #optional
description='''
XML Based Minecraft UI Library
'''